url: https://softwareblog.netlify.com/
highlighter: rouge

title: Jesse's Tech Blog

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts/default"
