url: http://jesseblog.surge.sh
highlighter: rouge

title: Jesse's Tech Blog

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts/default"
